---
- name: Bootstrap and Configure Pi Rack
  hosts: pis
  become: true
  gather_facts: true

  pre_tasks:
    - name: Ensure Python3 is available (bootstrap)
      ansible.builtin.raw: >
        test -e /usr/bin/python3 ||
        (apt-get update -qq && apt-get install -y -qq python3)
      changed_when: false

    - name: Gather facts
      ansible.builtin.setup:

  roles:
    - common
    - docker
    - role: elasticsearch
      when: inventory_hostname in groups['elasticsearch_nodes']

    - role: tailscale
      when: inventory_hostname in groups['tailscale_nodes']

    - role: tls
      when: inventory_hostname in groups['tls_nodes']

    - role: homeassistant
      when: inventory_hostname in groups['homeassistant_nodes']

  post_tasks:

    - name: Flush all handlers
      ansible.builtin.meta: flush_handlers
